
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMILLAS = 2;
  public static final int BOOL = 22;
  public static final int CLASEOPCIONES = 68;
  public static final int CREARU = 8;
  public static final int TITULO = 20;
  public static final int CORCHETEC = 38;
  public static final int CLASEBOTON = 70;
  public static final int CORCHETEA = 37;
  public static final int TEMA = 33;
  public static final int TITULOP = 29;
  public static final int CONSULTASP = 72;
  public static final int NUMERO = 45;
  public static final int OPCIONES = 57;
  public static final int OROP = 79;
  public static final int IDP = 28;
  public static final int CLASEIMAGEN = 69;
  public static final int FECHACP = 15;
  public static final int NOT = 77;
  public static final int USUARIOCP = 32;
  public static final int DEC = 23;
  public static final int NUEVOFP = 19;
  public static final int ELIMINARU = 17;
  public static final int FILAS = 58;
  public static final int CONTRAP = 14;
  public static final int CREDENCIALES = 64;
  public static final int LOGINU = 18;
  public static final int DOSP = 4;
  public static final int ELIMINARF = 34;
  public static final int NOMBREP = 30;
  public static final int SELECT = 74;
  public static final int ELIMINARC = 61;
  public static final int COMA = 48;
  public static final int PARAMF = 42;
  public static final int FINS = 47;
  public static final int CONSULTARD = 71;
  public static final int PARAMC = 62;
  public static final int SOLICITUDESP = 39;
  public static final int IGUAL = 80;
  public static final int FECHA = 27;
  public static final int USUARIOP = 9;
  public static final int CLASE = 52;
  public static final int NOMBREC = 44;
  public static final int USUARIONP = 12;
  public static final int FINE = 5;
  public static final int ERRORLEX = 84;
  public static final int ALINEAC = 55;
  public static final int COLUMNAS = 59;
  public static final int INDICEC = 53;
  public static final int INICIOS = 46;
  public static final int CLASENORMAL = 66;
  public static final int TEMAP = 31;
  public static final int AGREGARC = 43;
  public static final int DE = 76;
  public static final int USUARIO = 26;
  public static final int USUARIOAP = 11;
  public static final int URL = 50;
  public static final int MODIFICARU = 10;
  public static final int FECHAMP = 16;
  public static final int TEXTOVC = 54;
  public static final int EOF = 0;
  public static final int INICIOE = 3;
  public static final int WHERE = 75;
  public static final int MENORIGUAL = 82;
  public static final int MODIFICARF = 41;
  public static final int APOSTROFE = 83;
  public static final int MODIFICARC = 63;
  public static final int OR = 65;
  public static final int error = 1;
  public static final int FINSOLICITUDES = 40;
  public static final int CLASEAREA = 67;
  public static final int ID = 49;
  public static final int MENORQ = 7;
  public static final int ALINEA = 21;
  public static final int MAYORQ = 6;
  public static final int PARENTESISC = 25;
  public static final int NOCONSULTA = 73;
  public static final int PARENTESISA = 24;
  public static final int REQUERIDO = 56;
  public static final int MAYORIGUAL = 81;
  public static final int AND = 78;
  public static final int LLAVEC = 36;
  public static final int LLAVEA = 35;
  public static final int FORMULARIOC = 51;
  public static final int URLC = 60;
  public static final int NUEVOP = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMILLAS",
  "INICIOE",
  "DOSP",
  "FINE",
  "MAYORQ",
  "MENORQ",
  "CREARU",
  "USUARIOP",
  "MODIFICARU",
  "USUARIOAP",
  "USUARIONP",
  "NUEVOP",
  "CONTRAP",
  "FECHACP",
  "FECHAMP",
  "ELIMINARU",
  "LOGINU",
  "NUEVOFP",
  "TITULO",
  "ALINEA",
  "BOOL",
  "DEC",
  "PARENTESISA",
  "PARENTESISC",
  "USUARIO",
  "FECHA",
  "IDP",
  "TITULOP",
  "NOMBREP",
  "TEMAP",
  "USUARIOCP",
  "TEMA",
  "ELIMINARF",
  "LLAVEA",
  "LLAVEC",
  "CORCHETEA",
  "CORCHETEC",
  "SOLICITUDESP",
  "FINSOLICITUDES",
  "MODIFICARF",
  "PARAMF",
  "AGREGARC",
  "NOMBREC",
  "NUMERO",
  "INICIOS",
  "FINS",
  "COMA",
  "ID",
  "URL",
  "FORMULARIOC",
  "CLASE",
  "INDICEC",
  "TEXTOVC",
  "ALINEAC",
  "REQUERIDO",
  "OPCIONES",
  "FILAS",
  "COLUMNAS",
  "URLC",
  "ELIMINARC",
  "PARAMC",
  "MODIFICARC",
  "CREDENCIALES",
  "OR",
  "CLASENORMAL",
  "CLASEAREA",
  "CLASEOPCIONES",
  "CLASEIMAGEN",
  "CLASEBOTON",
  "CONSULTARD",
  "CONSULTASP",
  "NOCONSULTA",
  "SELECT",
  "WHERE",
  "DE",
  "NOT",
  "AND",
  "OROP",
  "IGUAL",
  "MAYORIGUAL",
  "MENORIGUAL",
  "APOSTROFE",
  "ERRORLEX"
  };
}

