
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym2 {
  /* terminals */
  public static final int COMILLAS = 2;
  public static final int BOOL = 22;
  public static final int CLASEOPCIONES = 80;
  public static final int CREARU = 8;
  public static final int TITULO = 21;
  public static final int CORCHETEC = 47;
  public static final int CLASEBOTON = 82;
  public static final int CORCHETEA = 46;
  public static final int TEMA = 40;
  public static final int TITULOP = 36;
  public static final int NUMERO = 56;
  public static final int OPCIONES = 68;
  public static final int CLASEIMAGEN = 81;
  public static final int IDP = 35;
  public static final int FECHACP = 16;
  public static final int USUARIOCP = 39;
  public static final int NUEVOFP = 20;
  public static final int ELIMINARU = 18;
  public static final int FILAS = 69;
  public static final int CONTRAP = 15;
  public static final int CREDENCIALES = 76;
  public static final int LOGINU = 19;
  public static final int DOSP = 4;
  public static final int ELIMINARF = 41;
  public static final int NOMBREP = 37;
  public static final int SELECT = 24;
  public static final int ELIMINARC = 73;
  public static final int COMA = 59;
  public static final int PARAMF = 51;
  public static final int FINS = 58;
  public static final int PARAMC = 74;
  public static final int SOLICITUDESP = 48;
  public static final int IGUAL = 27;
  public static final int FECHA = 34;
  public static final int USUARIOP = 9;
  public static final int CLASE = 63;
  public static final int NOMBREC = 53;
  public static final int USUARIONP = 12;
  public static final int FINE = 5;
  public static final int ALINEAC = 66;
  public static final int COLUMNAS = 71;
  public static final int INDICEC = 64;
  public static final int INICIOS = 57;
  public static final int CLASENORMAL = 78;
  public static final int TEMAP = 38;
  public static final int AGREGARC = 52;
  public static final int DE = 25;
  public static final int USUARIO = 33;
  public static final int CONSULTAS = 70;
  public static final int USUARIOAP = 11;
  public static final int URL = 61;
  public static final int MODIFICARU = 10;
  public static final int FECHAMP = 17;
  public static final int TEXTOVC = 65;
  public static final int FORM = 30;
  public static final int EOF = 0;
  public static final int INICIOE = 3;
  public static final int WHERE = 26;
  public static final int MODIFICARF = 50;
  public static final int MENORIGUAL = 42;
  public static final int APOSTROFE = 14;
  public static final int MODIFICARC = 75;
  public static final int OPERADORNOT = 54;
  public static final int OR = 77;
  public static final int error = 1;
  public static final int CONSULTADATOS = 55;
  public static final int OPERADORLOGICO = 43;
  public static final int FINSOLICITUDES = 49;
  public static final int CLASEAREA = 79;
  public static final int ID = 60;
  public static final int MENORQ = 7;
  public static final int MAYORQ = 6;
  public static final int PARENTESISC = 32;
  public static final int NOCONSULTA = 23;
  public static final int PARENTESISA = 31;
  public static final int REQUERIDO = 67;
  public static final int MAYORIGUAL = 28;
  public static final int LLAVEC = 45;
  public static final int TO = 29;
  public static final int LLAVEA = 44;
  public static final int FORMULARIOC = 62;
  public static final int URLC = 72;
  public static final int NUEVOP = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMILLAS",
  "INICIOE",
  "DOSP",
  "FINE",
  "MAYORQ",
  "MENORQ",
  "CREARU",
  "USUARIOP",
  "MODIFICARU",
  "USUARIOAP",
  "USUARIONP",
  "NUEVOP",
  "APOSTROFE",
  "CONTRAP",
  "FECHACP",
  "FECHAMP",
  "ELIMINARU",
  "LOGINU",
  "NUEVOFP",
  "TITULO",
  "BOOL",
  "NOCONSULTA",
  "SELECT",
  "DE",
  "WHERE",
  "IGUAL",
  "MAYORIGUAL",
  "TO",
  "FORM",
  "PARENTESISA",
  "PARENTESISC",
  "USUARIO",
  "FECHA",
  "IDP",
  "TITULOP",
  "NOMBREP",
  "TEMAP",
  "USUARIOCP",
  "TEMA",
  "ELIMINARF",
  "MENORIGUAL",
  "OPERADORLOGICO",
  "LLAVEA",
  "LLAVEC",
  "CORCHETEA",
  "CORCHETEC",
  "SOLICITUDESP",
  "FINSOLICITUDES",
  "MODIFICARF",
  "PARAMF",
  "AGREGARC",
  "NOMBREC",
  "OPERADORNOT",
  "CONSULTADATOS",
  "NUMERO",
  "INICIOS",
  "FINS",
  "COMA",
  "ID",
  "URL",
  "FORMULARIOC",
  "CLASE",
  "INDICEC",
  "TEXTOVC",
  "ALINEAC",
  "REQUERIDO",
  "OPCIONES",
  "FILAS",
  "CONSULTAS",
  "COLUMNAS",
  "URLC",
  "ELIMINARC",
  "PARAMC",
  "MODIFICARC",
  "CREDENCIALES",
  "OR",
  "CLASENORMAL",
  "CLASEAREA",
  "CLASEOPCIONES",
  "CLASEIMAGEN",
  "CLASEBOTON"
  };
}

