
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class symALM {
  /* terminals */
  public static final int NUMERO = 23;
  public static final int USUARIOCP = 18;
  public static final int CLASEIMAGEN = 42;
  public static final int NOMBREP = 16;
  public static final int COMPS = 46;
  public static final int CLASEBOTON = 43;
  public static final int FECHA = 12;
  public static final int PARENTESISC = 10;
  public static final int NOMBREC = 22;
  public static final int PARENTESISA = 9;
  public static final int TEXTOVC = 29;
  public static final int USUARIO = 11;
  public static final int INICIOFORM = 44;
  public static final int OR = 8;
  public static final int TITULOP = 15;
  public static final int BOOL = 7;
  public static final int TEMAP = 17;
  public static final int TITULO = 5;
  public static final int ID = 25;
  public static final int ALINEA = 6;
  public static final int FECHAMP = 36;
  public static final int EOF = 0;
  public static final int ALINEAC = 30;
  public static final int CONTRAP = 35;
  public static final int COMILLAS = 2;
  public static final int CLASE = 27;
  public static final int USUARIOP = 34;
  public static final int error = 1;
  public static final int COMA = 24;
  public static final int CLASEAREA = 40;
  public static final int URL = 26;
  public static final int IDF = 13;
  public static final int IDC = 14;
  public static final int TEMA = 19;
  public static final int DATOS = 47;
  public static final int REQUERIDO = 31;
  public static final int FECHACP = 4;
  public static final int CLASENORMAL = 39;
  public static final int INICIOUSUARIOS = 45;
  public static final int INDICEC = 28;
  public static final int DOSP = 3;
  public static final int NOREGISTRO = 48;
  public static final int URLC = 38;
  public static final int COLUMNAS = 37;
  public static final int CLASEOPCIONES = 41;
  public static final int FILAS = 33;
  public static final int LLAVEC = 21;
  public static final int LLAVEA = 20;
  public static final int OPCIONES = 32;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMILLAS",
  "DOSP",
  "FECHACP",
  "TITULO",
  "ALINEA",
  "BOOL",
  "OR",
  "PARENTESISA",
  "PARENTESISC",
  "USUARIO",
  "FECHA",
  "IDF",
  "IDC",
  "TITULOP",
  "NOMBREP",
  "TEMAP",
  "USUARIOCP",
  "TEMA",
  "LLAVEA",
  "LLAVEC",
  "NOMBREC",
  "NUMERO",
  "COMA",
  "ID",
  "URL",
  "CLASE",
  "INDICEC",
  "TEXTOVC",
  "ALINEAC",
  "REQUERIDO",
  "OPCIONES",
  "FILAS",
  "USUARIOP",
  "CONTRAP",
  "FECHAMP",
  "COLUMNAS",
  "URLC",
  "CLASENORMAL",
  "CLASEAREA",
  "CLASEOPCIONES",
  "CLASEIMAGEN",
  "CLASEBOTON",
  "INICIOFORM",
  "INICIOUSUARIOS",
  "COMPS",
  "DATOS",
  "NOREGISTRO"
  };
}

